### ISSUE TITLE
SSL Configuration

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#11]
With the current nginx config, I can't run the app locally. If I comment out the SSL stuff, it's fine.

This is true even when enable_ssl is false in the config.lua

**Comment by bromagosa** [comment]
Yes, because you need to generate local keys. Please wait until I'm done working with the migration, I can't handle all these issues now :(

**Comment by bromagosa** [comment]
Implemented in ea1079cf47a35292e995124c98489e039e996b97
