### ISSUE TITLE
User Activation Status Isn't Correctly Updated

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#112]
At first I thought it was a Snap! issue, but it's the cloud that isn't refreshing data.

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2179

**Comment by bromagosa** [comment]
Can this be closed now? :)

**Comment by cycomachead** [comment]
Oh, lame, I guess I forgot to use the right string in the pull request.
