### ISSUE TITLE
Setup dependencies with a rockspec

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#13]
Not to publish the package, but I think there's an easy way to install them all?

**Comment by bromagosa** [comment]
Easier than an sh script that does that for you? :)

I don't know, maybe you can look into it if you have the time.

**Comment by bromagosa** [comment]
Perfect, sounds good to me! :+1:

**Comment by bromagosa** [comment]
I'm not sure what's going on with this rockspec, but this is what I'm getting:

```
%sudo luarocks install snap-cloud-beta-0.rockspec
Using snap-cloud-beta-0.rockspec... switching to 'build' mode

Error: Directory snap.berkeley not found inside archive snap.berkeley.edu
```

Any ideas @cycomachead?

**Comment by bromagosa** [comment]
> That's weird. Are you running it from a directory named snap.berkeley.edu? Things currently install for me.

Nope, should I?

> Trying deleting the source section from the rockspec and see if that works? That's the only sensible place I could see snap.berkeley.edu making a difference.

This results in an error:

```Error: [...]/snapCloud/snap-cloud-beta-0.rockspec: Mandatory field source is missing.```

**Comment by cycomachead** [comment]
Nope, AFAIK running from the `snapCloud` cloud directory works. 

Ah, right. The source and url need to be there... Something is definitely related to the URL though, because if I delete the URL, then I see `Error: File not found: `.

It's perplexing how simple things can be so different!

**Comment by cycomachead** [comment]
Ah ha, I looked at some other rock specs, I think it needs to be `git://github.com:bromagosa/snapCloud.git` as the source URL.

Try that when you get a chance.
