### ISSUE TITLE
Server Maintenance 2018-09-29

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#147]
This is a set of notes / issues about the server maintenance on the weekend.

- [x] update lapis to latest + install rock spec
- [x] run all Ubuntu system updates
- [x] upgrade postgres to pg10
- [x] verify system hostname / setup process
- [x] script/steps to dump + restore DB
- [x] script to sync recently changed projects

**Comment by jmoenig** [comment]
Thanks, Michael! Do you think it's ready enough so we can notify users on the TEALS forum and on Piazza about the maintenance this upcoming weekend? If so I'd offer to do that, unless someone else wants to...

**Comment by cycomachead** [comment]
@jmoenig Yeah, this I think we should be able to do this. Could you please post the time as 11pm PST 9/28 to 4am PST 9/29? But I expect the actual migration to take only 2 hours. 

I think starting a tiny bit earlier will be a little bit easier and better for me, in the event something tricky pops up.

**Comment by bromagosa** [comment]
Best of luck in the migration!

When I'm back to work you'll have to walk me through all these changes.

**Comment by cycomachead** [comment]
Of course! And thanks. :)
