### ISSUE TITLE
Snap! (front end) should send down partially encrypted passwords

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#15]
The way the current Snap! front end works is that it hashes the passwords once, and then sends them down. 

Since that's the case, we can eliminate the prehash step here:
https://github.com/bromagosa/snapCloud/blob/master/validation.lua#L85

BTW, where is the new cloud.js is? Is it still the one in snapSite?

**Comment by bromagosa** [comment]
nope, it's in my snap fork (newer-cloud).

**Comment by cycomachead** [comment]
I know, but I'm saying it _should_ send down partially encrypted passwords. Even though the connection is https, encryption is useful in case the https connection is compromised -- which is sadly somewhat common when people use public networks. If it were exceedingly difficult, I'd say 'meh', but this one was easy. I have it done locally, both the front end and back end. I just need to clean up stuff and make a pull request.

**Comment by bromagosa** [comment]
Oh I see, I only replied to your last sentence :sweat_smile:

Sorry, there was an eternal flow of issues for me to read this morning, plus migration wasn't working because of a hard to trace memory issue.

This makes sense to me indeed, thanks!

**Comment by cycomachead** [comment]
Sorry! I didn’t mean for it to be a bombardment. :(

If you want to add me to the repo I’m happy to assign things to myself and separate them with milestones and whatnot. 

Also I just realized since we are talking about passwords: we should have the new cloud.js delete the old user data from local storage. (I guess we could even use that the first time to sign people in.)

**Comment by bromagosa** [comment]
You're a collaborator now :)

(What you say about local storage makes sense to me too)

**Comment by bromagosa** [comment]
This is done too now.
