### ISSUE TITLE
Look up my username API

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#158]
Users should be able to find accounts associated with an email address.

It should send an email to provide the details.

**Comment by bromagosa** [comment]
@cycomachead I've implemented this in https://github.com/bromagosa/snapCloud/tree/get_users_by_email, but how do we prevent people from spamming? If I was 12 and found out about this I'd be spamming my classmates all the time.

**Comment by cycomachead** [comment]
There’s nothing to prevent people from spamming to reset passwords either. 

I think there’s a few things:
* we don’t make this prominent but only on the forgot password page. (Either a separate form or a link to a second page
* we don’t send to the same email multiple times within a period. (This requires some tracking.)
* a general rate limiting system - also requires tracking but if we are concerned about abuse that’s usually the only thing.

**Comment by cycomachead** [comment]
Also this reminds me, we should treat emails as case insensitive too.

**Comment by bromagosa** [comment]
You're totally right. Let's keep it like this for a bit and we'll see how things develop. In the near future we can think of a rate limiting system.
