### ISSUE TITLE
Project Collections

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#164]
Project studios are a collection of projects. 

Schema:

```
project_collections:
name (string, not null)
creator_id (user_id, not null)
created_at (timestamp, not null)
updated_at (timestamp, not null)
description (string, nullable)
published (boolean, not null, default false)
published_at (timestamp, nullable)
shared (boolean, not null, default false)
shared_at (timestamp, nullable)
thumbnail_id (project_id, nullable)
```

and

```
collection_memberships:
collection_id (collection_id, not null)
project_id (project_id, not null)
created_at (timestamp, not null)
updated_at (timestamp, not null) -- not needed if lapis lets us skip it easily.
```

This is a good flexible base. I think there's a some things to think about before fully implementing:
* Extending to support multiple authors/owners
  * I think this is easy enough by adding a `collection_authors` table, which is basically a collection_id and a user_id, and those there have access to manage/edit or something.
  * We'd probably want to store who added a project to a collection, but that'd be easy too (add a user column to collection_memberships)
* Anything else?

**Comment by bromagosa** [comment]
That will work for now, yep! :)

**Comment by bromagosa** [comment]
Hey @cycomachead, any approximate date for this? I can work on it otherwise if you're too busy :)

**Comment by cycomachead** [comment]
I'm going to work on it Sunday. :)

**Comment by bromagosa** [comment]
This is done, only missing editor management and a bunch of permission checks. I'll open a new issue for the latter.
