### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#165]
We need to support a few user roles, from the current single admin boolean.

* normal user
* Reviewer. Can unpublish projects. Can delete comments.
* Moderator. Can unpublish and remove projects. Can delete comments. Can block users. Can delete users.
* admin

We should use a postgres enum for this.
```
CREATE TYPE snap_user_role AS ENUM ('standard', 'reviewer', 'moderator', 'admin')
```

Steps to migrate:
* create type
* create role column with type `snap_user_role`
* fix current admin users roles. i.e. `UPDATE users .... WHERE is_adim = true`
* Drop the admin column

This will be flexible enough to add new roles, `ALTER TYPE` will let us add new values.

In lapis we should define functions on the user for `user:can_view(object)` or `user:can_delete(object)` etc.

**Comment by bromagosa** [comment]
Working on this now :)

**Comment by bromagosa** [comment]
This can be closed, I think. We still need logic for different permissions, but user roles are done and working :)
