### ISSUE TITLE
Fix Lazy Notes Generation to Handle Empty Notes

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#167]
See #125 for how we got here.

* we need to adjust the check in api.lua#L420 to only check for nil notes
* the XML parse_notes function should return an empty string after parsing a project.

**Comment by bromagosa** [comment]
It was almost faster to fix this than to write this comment :laughing: 

Thanks for the thorough investigation!

**Comment by cycomachead** [comment]
I'm not sure the fix is working quite right. Or least, this also points to something else being an issue. After running that request, none of our projects should have null notes. It seems to have worked for you account but not Bernat's.

```
snapcloud=> SELECT COUNT(*) FROM projects WHERE username = 'cycomachead' and notes is null;
 count 
-------
   121
(1 row)

snapcloud=> SELECT COUNT(*) FROM projects WHERE username = 'jens' and notes is null;
 count 
-------
   280
(1 row)
```

**Comment by bromagosa** [comment]
Uhm... that's weird. Can you take a look? I'm working on the site now...

Btw, did you have time to work on collections? I'll do that next starting tomorrow otherwise. I'm about to run out of stuff to do...

**Comment by bromagosa** [comment]
(my username is *bromagosa*, *bernat* is just a test account with barely any projects :wink:)

**Comment by cycomachead** [comment]
The XML library is returning nil from the line `notes = xml.find(project, 'notes')[1]` 

I guess there's a really easy fix here: `return notes or ''`. I just can't tell if the XML library distinguishes between empty strings and nil at all.

**Comment by bromagosa** [comment]
This is working now. Good! :)

**Comment by cycomachead** [comment]
Yay! 2.29s → .48s for my project list.

And I'll have a start to the collections up in a bit. I got more distracted today looking into this.
