### ISSUE TITLE
Don't actually delete projects

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/snapCloud#169]
I've decided to add a `deleted` timestamp column. I've been running some benchmarks in staging and it doesn't add too much overhead to test whether an additional column is `null`. We could even create a view that filters deleted projects automatically and always query from that one except when specifically looking for deleted projects:

`create view active_projects as select * from projects where deleted is null;`
`create view deleted_projects as select * from projects where deleted is not null;`

This will make it much easier for remixes, as it won't break any existing relationships.

**Comment by cycomachead** [comment]
Can we name the column `deleted_at`? Otherwise, it seems like `deleted` is probably a boolean.

**Comment by bromagosa** [comment]
Hmm, we can, but I was just following the same names as `created`, `lastshared`, etc.

**Comment by cycomachead** [comment]
I think we should name those with `_at` too. Especially since there's some useful features in lapis: http://leafo.net/lapis/reference/models.html#timestamps

**Comment by bromagosa** [comment]
Agreed. I'll close this one though, as it's already implemented in 78679cc. We can rename these columns later :)

I'm amazed at how easy it was to do this, by the way. Views are very useful.

**Comment by cycomachead** [comment]
Views are indeed cool! I really like that solution.

The other cool thing is that those views also will show up in metabase, too.
--
Michael Ball | michaelball.co
UC Berkeley Computer Science BA '15, MS '16
gradescope.com | bjc.berkeley.edu
