### ISSUE TITLE
Shared Projects and Public Collections

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#178]
Right now, my intent is that you can't add a _shared_ project to a collection unless you own that collection. 

The reason is that shared projects aren't searchable, but a public collection will be findable. 

The proper solution is to let you add a shared project to non-public collections, but this complicates making a collection public, so I think we should wait for that.

**Comment by bromagosa** [comment]
Oh wait, you already had an issue for that. I'm closing it in favor of #208 :)
