### ISSUE TITLE
Support Multiple Editors For Collections

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#180]
I think we can add an `editor_id[]` array field to the collections table. 

We should add a `user_id` field to collection_memberships, but I want to do that anyway.

**Comment by bromagosa** [comment]
Everyone should be able to add projects to snapcloud's "Flagged" collection, but the `editor_ids[]` field doesn't help with that, unless we add all users to it :sweat_smile:

Should we just special case this particular collection? I don't foresee having any other project collections that everybody can write to.

Another option would be to add an `adder_usertypes[]` field that lists user types who can add projects to a collection without being in the `editor_ids[]` array. In this case, it'd contain `standard` so everyone can add to it.

**Comment by cycomachead** [comment]
Yeah the flagged collection should be special. 

It should be special in a few ways - namely anyone can edit, but not view, and we will probably customize its view overtime.  The flagged collection is likely the only collection where a project will appear multiple times, so eventually we might do things to help deal with that (like sorting and grouping projects). 

But for now, I think we should just hard code the name / id into the app. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by bromagosa** [comment]
Missing:

- [ ] Add editor to collection: `POST /user/:username/collections/:collectionname/editors`
- [ ] Remove editor from collection: `DELETE /user/:username/collections/:collectionname/editors/:editorusername`
- [ ] Get editors from collection: `GET /user/:username/collections/:collectionname/editors`
