### ISSUE TITLE
Delete tokens in user delete

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#183]
To avoid violating foreign key constraints

**Comment by bromagosa** [comment]
Yep, but actually the current plan is to _not_ delete users. We'll flag them as deleted, same thing we do with projects.

Then in the (fairly near) future we can add tools to clean up projects and users that were deleted n months ago.

**Comment by bromagosa** [comment]
Closing this as deleting a user now flags it as deleted. In the future, we can add these tools to look for deleted users and so on, but right now tokens will just expire and die after a while.
