### ISSUE TITLE
Use 404 errors for private things that do exist

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#191]
IMO we should switch to this over 401's. It's not a huge issue, but revealing that something exists can potentially be info someone doesn't want to get out. GitHub for example does not reveal that private projects exist. https://github.com/cs10/keys should return a 404 for most people.

**Comment by bromagosa** [comment]
Good point. I guess there are advantages and disadvantages to both. Example:

I have two accounts, I try to access a private project from my other account via URL, the system tells me the project does not exist, I panic.

But yeah, these are just details. I'm okay with your proposal. I can do it today, it's one of these "easier to do than to file an issue" things.
