### ISSUE TITLE
Don't query anything for OPTIONS requests

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#202]
If the method type is OPTIONS we shouldn't execute the before filter.

OPTIONS never need to query any data just handle the CORS issues.

**Comment by bromagosa** [comment]
Actually, I'm pretty confident that `before_filter` does never run for OPTIONS request.

I've added a `print(ngx.get_method())` in the `before_filter` and it only prints `POST`s and `GET`s (and I assume `DELETE`s too).

**Comment by cycomachead** [comment]
Hmm, I sent an options request locally and saw SQL statements in the logs. Maybe something else was causing a query then....

**Comment by bromagosa** [comment]
You're right, I will retest this on different origins when I've some spare time.

**Comment by bromagosa** [comment]
Now it's done :)

**Comment by cycomachead** [comment]
Cool. :) thanks!

-- 
Michael Ball
From my iPhone
michaelball.co
