### ISSUE TITLE
Permission checks for collections

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/snapCloud#208]
- [x] When a collection is public, hide its shared and private projects from users that don't have read permission
- [x] When a collection is shared, hide its private projects from users that don't have read permission

**Comment by cycomachead** [comment]
Should we warn users when they add a project to a collection with the different permissions.

**Comment by cycomachead** [comment]
Should we warn users when they add a project to a collection with the different permissions — mostly a front-end thing I suppose, but maybe the API could return that as a message. 

Also I think editors should be able to see all shared projects in a collection? Probably...though I can see a reason for not doing it, but I think showing them makes it easier to collaborate.

**Comment by cycomachead** [comment]
Whoops. Buttons are hard. 😉
