### ISSUE TITLE
Zombie user administration

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/snapCloud#215]
Tools to deal with deleted users:

- [x] `GET /zombies` gets a list of all zombies. Parameters to filter and search.
- [x] `POST /zombies/:username/revive` brings a zombie back to userland.
- [x] `DELETE /zombies/:username` gets rid of a zombie forever.

**Comment by bromagosa** [comment]
@cycomachead right now you can't delete a zombie user if they own any projects or collections. My hunch is that `TRUNCATE ... CASCADE` should do the trick, but I'm a bit scared it could delete things we don't want to, so my proposal is:

* Manually go through all projects belonging to that user and delete them, both from the DB and from disk.
* Manually go through all collections belonging to that user and:
  - Delete them if they have no extra editors.
  - Assign a random editor to be their new owner if they do.
* Remove the user from all collections from which they're editors.

This can be a bit costly, but we don't delete users everyday (only 5 users have been deleted in the past 6 months, and two of them are tests of mine).

Opinions? :)

**Comment by bromagosa** [comment]
Closing because all functionalities are now there, although we need to revisit deletion.

**Comment by cycomachead** [comment]
I think that makes sense. We could have a “ghost” user like GitHub does that is the owner of deleted things that need to stick around. That may be safer than assigning a random editor, but right now the permissions aren’t really different so random seems easiest.

**Comment by cycomachead** [comment]
I also agree that manually deleting them seems fine.

**Comment by bromagosa** [comment]
:+1: thanks!

These are all implemented now :)
