### ISSUE TITLE
lowercase() username in a before hook?

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#25]
Why not do it once before any request is processed? Otherwise, we're bound to slip up.
Like here, https://github.com/bromagosa/snapCloud/blob/master/app.lua#L89

**Comment by bromagosa** [comment]
That's a valid point. I wanted the query response to contain the username in the same format it arrived, so that if you always log in as "Michael", the response read "User Michael logged in", but I guess that's not worth possibly missing a call to `lower()` in the future.

**Comment by cycomachead** [comment]
That was fast. :)

And yeah, I think if users end up being confused / picky we could add `self.params.raw_username` or something. Then it's clear what's being displayed where.
