### ISSUE TITLE
Set Proper response codes

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#32]
Right now, everything returns 200. 

Most of these should be straightforward, but I think we should also take case with accessing an existing private project project. 
We're should probably say "This project doesn't exist" and return a 404, not a 403. (And definitely not a 200).

**Comment by bromagosa** [comment]
Yeah, although the only two client-side apps that access the backend are ours, so this is mostly cosmetic.

We desperately need a test environment. I don't want a syntax error to break the production environment when we're testing simple changes like this one...

**Comment by cycomachead** [comment]
It’s not totally cosmetic because it makes logging and monitoring significantly easier. But I don’t think we should think of this as only 2 applications. There were things I needed to do with the old api as a TA and any api with proper response codes is much easier to grok. 

But yes. I can try to setup a test drop.et later. Can you run the app locally on your ,a nine. It’s not an exact configuration but that’s how I’ve been testing things. 

Additionally I think we should setup busted at some point.
