### ISSUE TITLE
Do not send verification email to verified users

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/snapCloud#33]
If a user is already verified and asks for a verification link, send an email informing that the account is already verified instead.

**Comment by cycomachead** [comment]
We should also return a response that says that the user is verified and there will be confirmation.

**Comment by bromagosa** [comment]
Instead of an email, I'm returning a response saying that the user is verified. Snap! will show that to users in a cloud dialog, we don't need to clutter people's email accounts.

(closed in 4112c3de4a48529691685b54d5f9f3b821a094fa)
