### ISSUE TITLE
Allow users to change their emails

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#36]
It seems like a few of the undelivered emails are probably typos. We should allow users to change their account email, and then reset the verification process.

**Comment by bromagosa** [comment]
Hmm, how do you do that when you can't login? We can't allow people to change an account email without knowing it's theirs, and we can't know it's theirs unless they log in.

I can add a "change my email" option but only to logged in users.

**Comment by cycomachead** [comment]
So, the verification problems seem to be, in part, people who sign up and know their password but can't verify. Right now your solution would be to create a new account, but if you know your username and password I think you can change your email. 

I think it makes sense to allow changing an email if your account is verified, or within the verification period -- and probably after the window? if you know the account password it seems safe to allow you to more easily get a verification email if your existing system is treating things as spam or something.

**Comment by bromagosa** [comment]
Yes, it makes sense to change your password if you're logged in, indeed.

I can add this to the cloud menu :)
