### ISSUE TITLE
Something is weird with sessions

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#37]
When I visited /users/c it for my account is says `{"isadmin":false,"username":"cycomachead"}`

When I do /users/cycomachead I see: `{"isadmin":true,"created":"2018-01-25 15:53:39.669+00","username":"cycomachead","email":"cycomachead@gmail.com"}`

I'm was also seeing the "Your account is not verified" message.

When I logged out, then logged back in, both the /users/c endpoint and the (absence of) the message in Snap! were correct.

**Comment by bromagosa** [comment]
Right, let me work on this today.

Initially, `users/c` was only meant to test the username of the current session. I added the `isadmin` parameter later because I needed that in the social site. I now need to add `verified` to that response as well. That query should **not** be cached though. I'll check.

`/users/[username]` returns a more exhaustive record, but only to admins.

**Comment by bromagosa** [comment]
According to the code for `users/c`, this query should not be being cached at all.

The only suspicious thing I can find is the line:
```
self.res.headers['Vary'] = 'Origin'
```
Mozilla says:

> The Vary HTTP response header determines how to match future request headers to decide whether a cached response can be used rather than requesting a fresh one from the origin server.

But I didn't even know about this header and I don't know what we need it for, so it may not be the cause for the problem at all.

**Comment by bromagosa** [comment]
Oh, now I see!

We're actually sending the verified info in the `users/c` response, but we're reading it from the session. So, if you logged in permanently before I made the changes, your session will not have your `verified` information.

Does that make sense?

I'm going to check whether I can kill all live sessions.

**Comment by bromagosa** [comment]
Fixed. In `/users/c` I'm checking whether the verified field actually exists in `self.session`. If now, I'm pulling it from the DB.

Users that were already logged in prior to the verification check updates should now not be receiving the annoying message anymore.
