### ISSUE TITLE
Monitor logging level.

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#39]
I adjusted the log in nginx.conf to log to logs/error.log -- notice seems to be quite noisy. It should be fine for now but we might want to turn it down. Logging query times is helpful for now. Things are good. :)

**Comment by bromagosa** [comment]
Great! :)

(closing this)

**Comment by cycomachead** [comment]
Well, I don't know why nginx counts success notices in the error log, but there was different info. 

In general, the error log should have 404's, 500's etc.

**Comment by bromagosa** [comment]
Hmm, interesting. I'll take a look tomorrow :)

**Comment by cycomachead** [comment]
I need to tweak the configuration and make a PR. I think it might make sense to set it to ‘warning’ — though the query times are a useful monitoring metric for now. 

-- 
Michael Ball
From my iPhone
michaelball.co
