### ISSUE TITLE
More Detailed Logging / Error Reporting

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#52]
https://amplify.nginx.com/docs/guide-metrics-and-metadata.html#additional-nginx-metrics

I set up some monitoring, up to this point, but this involves just tweaking the log format.

**Comment by bromagosa** [comment]
Why do we need so much overhead and fancy graphs? :worried:

Are you even sure this will work with our current openresty setup?

Are there really so many errors? I'm very happy grepping the logs in plain text format.

**Comment by cycomachead** [comment]
There's not that much overhead at all. (Well this does somewhat obsolete the digital ocean agent).

Anyway, yes, I'm sure. It's working now and I tested it before installing things. The agent works by watching the regular nginx logs and by using some simple metrics from nginx's (builtin) stub_status module. 

The problem monitoring solves isn't so much of grepping through logs, but getting a better view historical data. There really aren't that many errors, which is great. But seeing the trend lines are exceptionally helpful, especially if we're going to need to make reasonable cost predictions. Plus, in the case of yesterday, it's reassuring to know when virtually no one is using the site.
