### ISSUE TITLE
Setting Up A Staging Server.

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#57]
I'm mostly done configuring the staging server, but we need to do a few more things:
It's snap-staging.cs10.org for now.

- [x] create a local DB instance on the staging server
- [x] expose a `staging` config in config.lua
- [x] update the allowed domains
- [x] update snap to point to the staging server
- [x] consider getting a berkeley SSL cert?
- [x] setup http basic auth? So people don't accidentally use the wrong server.

Eventually, I think we should setup a script to extract a subset of data from the production server to the staging server. (Done for admins; it can easily be extended for others.)

**Comment by cycomachead** [comment]
I'm documenting my process here, but this is what I have done:

* Create the smallest DO droplet
* Initialize with an SSH key
* Create a `cloud` user account
* Make a new SSH key tied to my github account. This should later be made @snap-bot or @snapcloud (if I can find the email for that....)
* Installed some dependencies:
    * pg 9.5
    * authbind
    * go + hub (See github/hub)
    * sshfs
* Cloned the repo and ran the install script
* Copied the daemon into /etc/init.d/
* On the main server: as root: `su - postgres; pg_dumpall > /db_backup/db.out`
* On staging:
   * scp the backup
   * start postgres service
   * `pg_restore -C -f /db-temp/db.out`

**Comment by cycomachead** [comment]
Fixed with #71

**Comment by bromagosa** [comment]
Great job, Michael!!!

**Comment by cycomachead** [comment]
Thanks!
