### ISSUE TITLE
Snap! SSL Issues Thread

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#62]
Putting any info here to log the work that's done, and note progress etc.

Useful sites:
* https://calnetweb.berkeley.edu/calnet-technologists/incommon-comodo-certificate-service/extended-incommon-ssl-certificate-example
* https://www.sslshopper.com/ssl-checker.html#hostname=snap.berkeley.edu
* https://www.sslshopper.com/ssl-checker.html#hostname=cloud.snap.berkeley.edu

**Comment by cycomachead** [comment]
snap.berkeley.edu has been fully fixed. There is work that needs to be done on the cloud server. 

EECS was able to regenerate the cert for s.b.e and swapped the ordering of intermediate certs.

**Comment by jmoenig** [comment]
Yay!

**Comment by cycomachead** [comment]
I've figured out what I need for the cloud server. I will work on this tonight.
