### ISSUE TITLE
Delete user does not work

### ISSUE THREAD

**Issue by aaaschmitt** [bromagosa/snapCloud#79]
It looks like this code should not work because the `user` variable is not defined:

```
    DELETE = capture_errors(function (self)
        assert_all({'logged_in', 'admin'}, self)

        if not (user:delete()) then
            yield_error('Could not delete user ' .. self.params.username)
        else
            return okResponse('User ' .. self.params.username .. ' has been removed.')
        end
    end)
```

I think someone just forgot to query for it. Or maybe I just don't know anything about lua...

**Comment by bromagosa** [comment]
Yep, it's missing a:

```
local user = Users:find(self.params.username)
```

But actually there's no UI-side user deletion mechanism, so this was just a placeholder for when we add one.
