### ISSUE TITLE
Don't show `.html` extensions in the social site. 

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#85]
Ok, this is purely cosmetic, but I like pretty URLs. 

Fortunately, it's pretty easy to hide the .html and have a safe fallback:

```
  try_files  site/$uri site/$uri.html site/$uri/index.html site/index.html;
```

**Comment by bromagosa** [comment]
Wait, this doesn't work when there are params in the URL... investigating.

**Comment by bromagosa** [comment]
Nah, yes it does. I just need to tweak a bunch of hrefs in the social site.

**Comment by bromagosa** [comment]
done in https://github.com/bromagosa/SnapSite/commit/5a10bb19255a9afc3d16821673d2d07e1d37adf4

**Comment by cycomachead** [comment]
Thanks for doing this! URLs look nice! :)
