### ISSUE TITLE
User With Multiple Valid Verification Tokens

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#91]
Need to investigate how this happened, but this user had 3 tokens (until I used one) and now there 2 valid `verify_user` tokens. 

https://snap-analytics.herokuapp.com/question/69

**Comment by bromagosa** [comment]
They must have clicked "resend verification email" a bunch of times?

We could make sure a new token isn't created every time. This isn't a serious bug though, as all tokens will expire and be deleted automatically anyway :)
