### ISSUE TITLE
Consider Prefixing routes with /api or a version 

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#92]
We don’t need to do this, and certainly not immediately, but I think it’s worth considering. 

Using a /api prefix (or anything unique really) gives us the flexibility to host static pages and the API on the same server without worrying about conflicts. It doesn’t seem unreasonable to deploy the social front end to the same server. 

Similarly, a version identifier allows us to more easily make big changes going forward without worrying about breaking a current client’s use. That could be as simple as not having to update the social site at the same time as deploying a backend feature but it could also be about more easily working with research projects. 

Versions could be part of the URL or an HTTP header, but I usually fine putting them towards the front of the URL to be easy, I.e. /v1/projects....

Combined together we could preview API routes with /api/v1, but simply using /v1 as a prefix would work too because it’s not likely to conflict with something else. 

Anyways, like I said, this isn’t urgent but something to consider since it’s a change that’s easier to make when there’s less usage.

**Comment by bromagosa** [comment]
Yep. Actually I used the `api` prefix in the BeetleCloud but decided against it here because, initially, the server was meant to host only the API. Since we're hosting more stuff now, prefixing the API sounds totally reasonable.
